# Change these first
owner: thematters # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Matters (matters.news)
    url: https://matters.news/
  - name: Matters (API)
    url: https://server.matters.news/playground
  - name: Matters (IPFS)
    url: https://ipfs.io/ipfs/QmNXVLMMLEq8XHtErBh3NFBetGt29wD7V2aXDp29Q4Lo4C
  - name: Matters (Landing Page)
    url: http://matters-lab.io/
  - name: The Space (Landing Page)
    url: https://www.thespace.game/
  - name: The Space (App)
    url: https://app.thespace.game/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.matters.news
#   baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/thematters/uptime/master/assets/logo.svg
  name: Matters Status
  introTitle:
  introMessage:
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  themeUrl: https://matters.news/custom-theme.css

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
